### ISSUE TITLE
Add cluster-role/cluster-role-binding support

### ISSUE THREAD

**Issue by korjek** [jtopjian/terraform-provider-sensu#24]
Hello.

This is a feature request.

There is no possibility to create cluster-role/cluster-role-binding with sensu provider.
That would be great if the support of cluster-role/cluster-role-binding added to sensu provider.

**Comment by jtopjian** [comment]
@korjek I apologize for the late reply. I only have a limited amount of time to work on this provider currently, so I'm not sure when I'd be able to get to this. I'm happy to review PRs for it, though.

**Comment by jtopjian** [comment]
Implemented in #29
