### ISSUE TITLE
"runtime_assets" not supported for sensu handlers

### ISSUE THREAD

**Issue by vinkris** [jtopjian/terraform-provider-sensu#4]
Any reason why "runtime_assets" are not supported for sensu handlers? It seems like you're supporting "runtime_assets" for sensu checks already. 

This can probably not let anyone using this provider to configure handlers properly.

**Comment by jtopjian** [comment]
No reason that I'm aware of 🙂 

It was probably just overlooked.

**Comment by vinkris** [comment]
Ok. It would be great if this can be fixed. I can't seem to create handlers properly without this fixed.
Thank you 👍

**Comment by jtopjian** [comment]
@vinkris I've opened #5 to address this. If you're able to compile from source, please let me know if this looks good.

**Comment by vinkris** [comment]
@jtopjian looks good, I have tested the changes. It works as expected.
