### ISSUE TITLE
Environment Variables don't update on Check Resource

### ISSUE THREAD

**Issue by DanRoberson** [jtopjian/terraform-provider-sensu#41]
It looks like this function isn't tracking changes to `env_vars` defined on the Check resource.

https://github.com/jtopjian/terraform-provider-sensu/blob/9cb3802d00e275e387b4dbcd51f34978452affd9/sensu/resource_check.go#L362

**Comment by jtopjian** [comment]
@DanRoberson Sorry for the late reply. Thank you for reporting this. I hope to be able to address it shortly.

**Comment by DanielRoberson** [comment]
No problem, I was going to open a PR, just haven't had time unfortunately. The problem I'm trying to solve though is that Environment Variables aren't getting updated even though they show as changed when running a `terraform plan/apply`.  They don't update in Sensu-Go.

**Comment by jtopjian** [comment]
@DanRoberson This has been fixed in #42. There should be a v0.10.6 release published shortly which includes it.
