### ISSUE TITLE
Probably a better idea to compile this provider with static binaries?

### ISSUE THREAD

**Issue by vinkris** [jtopjian/terraform-provider-sensu#6]
I have tried to run this provider on Alpine docker image, and I keep getting this error on terraform plan/apply:

`* provider.sensu: fork/exec /tmp/prod/us-east-2/sensu/sensu-config/.terraform.d/plugins/linux_amd64/terraform-provider-sensu_v0.4.0_x4: no such file or directory
`

On a quick google search to see if there are any other providers which hit this issue, I found that the same issue was encountered by terraform-provider-helm.

Here are some links which helped me find the workaround of using libc6-compat package:
https://github.com/terraform-providers/terraform-provider-helm/issues/104
https://github.com/terraform-providers/terraform-provider-helm/pull/111

**Comment by jtopjian** [comment]
@vinkris This should be working with [v0.5.0](https://github.com/jtopjian/terraform-provider-sensu/releases/tag/v0.5.0). Please let me know if you're still having problems.

**Comment by vinkris** [comment]
Thanks @jtopjian for the help. Will check it out.
